#!/usr/bin/env node
/**
 * Installs a post-commit git hook that auto-rebuilds codebase-index.json
 * after every commit.
 *
 * Usage: node scripts/install-hooks.js
 */

const fs = require("fs");
const path = require("path");

const HOOK_NAME = "post-commit";
const HOOK_CONTENT = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js
# Rebuild codebase-index.json after every commit.

cd "$(git rev-parse --show-toplevel)"
node scripts/index-codebase.js
`;

const gitDir = path.resolve(__dirname, "..", ".git");
const hooksDir = path.join(gitDir, "hooks");
const hookPath = path.join(hooksDir, HOOK_NAME);

// Ensure .git/hooks exists
if (!fs.existsSync(hooksDir)) {
  console.error("❌ .git/hooks not found — not a git repo?");
  process.exit(1);
}

// Write the hook
fs.writeFileSync(hookPath, HOOK_CONTENT, { mode: 0o755 });
console.log(`✅ Installed .git/hooks/${HOOK_NAME}`);
